package com.coachfit.auth.adapter.in;

import com.coachfit.auth.adapter.in.dto.AuthResponse;
import com.coachfit.auth.adapter.in.dto.UserDto;
import com.coachfit.auth.application.port.in.GoogleOAuthUseCase;
import com.coachfit.auth.domain.model.AuthUser;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseCookie;
import org.springframework.web.bind.annotation.*;
import com.coachfit.auth.application.service.GoogleOAuthService;

import java.io.IOException;
import java.security.SecureRandom;
import java.time.Duration;
import java.util.HexFormat;

/**
 * Controller for Google OAuth2 OIDC flow.
 *
 * <pre>
 * GET /api/v1/auth/oauth/google           → 302 redirect to Google auth page
 * GET /api/v1/auth/oauth/google/callback  → exchange code, issue JWT, redirect to frontend
 * </pre>
 *
 * <h3>State (CSRF protection)</h3>
 * A 16-byte random hex state is generated on initiation and stored in Redis with a 5-minute TTL.
 * The callback verifies the state is present (was generated by this server) before proceeding.
 */
@RestController
@RequestMapping("/api/v1/auth/oauth/google")
public class GoogleOAuthController {

    private static final Logger log = LoggerFactory.getLogger(GoogleOAuthController.class);

    private static final String COOKIE_NAME    = "refresh_token";
    private static final String COOKIE_PATH    = "/api/v1/auth";
    private static final String STATE_KEY_PREFIX = "oauth_state:";

    private final GoogleOAuthService   googleOAuthService;
    private final GoogleOAuthUseCase   googleOAuthUseCase;
    private final StringRedisTemplate  redisTemplate;
    private final String               appUrl;
    private final boolean              cookieSecure;
    private final SecureRandom         secureRandom = new SecureRandom();

    public GoogleOAuthController(GoogleOAuthService googleOAuthService,
                                 GoogleOAuthUseCase googleOAuthUseCase,
                                 StringRedisTemplate redisTemplate,
                                 @Value("${app.url}") String appUrl,
                                 @Value("${app.security.refresh-cookie-secure:true}") boolean cookieSecure) {
        this.googleOAuthService = googleOAuthService;
        this.googleOAuthUseCase = googleOAuthUseCase;
        this.redisTemplate      = redisTemplate;
        this.appUrl             = appUrl;
        this.cookieSecure       = cookieSecure;
    }

    // ── GET /auth/oauth/google — initiate ─────────────────────────────────────

    @GetMapping
    public void initiateOAuth(HttpServletResponse response) throws IOException {
        String state   = generateState();
        redisTemplate.opsForValue().set(STATE_KEY_PREFIX + state, "1", Duration.ofMinutes(5));

        String authUrl = googleOAuthService.buildAuthorizationUrl(state);
        log.debug("Redirecting to Google OAuth: {}", authUrl);
        response.sendRedirect(authUrl);
    }

    // ── GET /auth/oauth/google/callback ───────────────────────────────────────

    @GetMapping("/callback")
    public void handleCallback(@RequestParam String code,
                               @RequestParam String state,
                               HttpServletResponse response) throws IOException {

        // Verify state to prevent CSRF
        Boolean stateExists = redisTemplate.hasKey(STATE_KEY_PREFIX + state);
        if (!Boolean.TRUE.equals(stateExists)) {
            log.warn("Google OAuth callback received invalid or expired state");
            response.sendRedirect(appUrl + "/auth/error?reason=invalid_state");
            return;
        }
        redisTemplate.delete(STATE_KEY_PREFIX + state);

        GoogleOAuthUseCase.AuthResult result = googleOAuthUseCase.handleCallback(code);

        // Set httpOnly refresh token cookie
        response.addHeader(HttpHeaders.SET_COOKIE, refreshCookie(result.rawRefreshToken()).toString());

        // Redirect frontend to a page that reads the access token from the URL fragment.
        // The token is short-lived (1h) so URL transit is acceptable.
        // Frontend should immediately move it to in-memory storage.
        response.sendRedirect(appUrl + "/auth/callback?token=" + result.accessToken());
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private String generateState() {
        byte[] bytes = new byte[16];
        secureRandom.nextBytes(bytes);
        return HexFormat.of().formatHex(bytes);
    }

    private ResponseCookie refreshCookie(String rawToken) {
        return ResponseCookie.from(COOKIE_NAME, rawToken)
                .httpOnly(true)
                .secure(cookieSecure)
                .path(COOKIE_PATH)
                .maxAge(Duration.ofDays(30))
                .sameSite("Strict")
                .build();
    }

    private UserDto toUserDto(AuthUser user) {
        return new UserDto(user.id(), user.email(), user.fullName(), user.role(), user.tier());
    }
}
