package com.coachfit.auth.adapter.in;

import com.coachfit.auth.adapter.in.dto.AuthResponse;
import com.coachfit.auth.adapter.in.dto.UserDto;
import com.coachfit.auth.application.port.in.StravaOAuthUseCase;
import com.coachfit.auth.application.service.StravaOAuthService;
import com.coachfit.auth.domain.model.AuthUser;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseCookie;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.security.SecureRandom;
import java.time.Duration;
import java.util.HexFormat;

/**
 * Controller for Strava OAuth2 authorization-code flow.
 *
 * <pre>
 * GET /api/v1/auth/oauth/strava           → 302 redirect to Strava auth page
 * GET /api/v1/auth/oauth/strava/callback  → exchange code, issue JWT, redirect to frontend
 * </pre>
 *
 * <h3>State (CSRF protection)</h3>
 * A 16-byte random hex state is generated on initiation and stored in Redis with a 5-minute TTL.
 * The callback verifies the state is present (was generated by this server) before proceeding.
 * See docs/08-auth-model.md §Security Checklist.
 *
 * <h3>Error handling</h3>
 * Any errors (invalid state, Strava API failure) redirect to {@code /auth/error} on the frontend
 * with a {@code reason} query param — never expose stack traces in OAuth redirects.
 */
@RestController
@RequestMapping("/api/v1/auth/oauth/strava")
public class StravaOAuthController {

    private static final Logger log = LoggerFactory.getLogger(StravaOAuthController.class);

    private static final String COOKIE_NAME      = "refresh_token";
    private static final String COOKIE_PATH      = "/api/v1/auth";
    private static final String STATE_KEY_PREFIX = "oauth_state:strava:";

    private final StravaOAuthService  stravaOAuthService;
    private final StravaOAuthUseCase  stravaOAuthUseCase;
    private final StringRedisTemplate redisTemplate;
    private final String              appUrl;
    private final boolean             cookieSecure;
    private final SecureRandom        secureRandom = new SecureRandom();

    public StravaOAuthController(StravaOAuthService stravaOAuthService,
                                 StravaOAuthUseCase stravaOAuthUseCase,
                                 StringRedisTemplate redisTemplate,
                                 @Value("${app.url}") String appUrl,
                                 @Value("${app.security.refresh-cookie-secure:true}") boolean cookieSecure) {
        this.stravaOAuthService = stravaOAuthService;
        this.stravaOAuthUseCase = stravaOAuthUseCase;
        this.redisTemplate      = redisTemplate;
        this.appUrl             = appUrl;
        this.cookieSecure       = cookieSecure;
    }

    // ── GET /auth/oauth/strava — initiate ─────────────────────────────────────

    /**
     * Redirects the browser to Strava's OAuth authorization page.
     *
     * <p>Docs/06-sync-engine-spec.md §Strava OAuth Flow step 2:
     * "Redirect → https://www.strava.com/oauth/authorize?client_id=...&scope=activity:read_all..."
     */
    @GetMapping
    public void initiateOAuth(HttpServletResponse response) throws IOException {
        String state = generateState();
        // Store state in Redis with 5-minute TTL to prevent CSRF
        redisTemplate.opsForValue().set(STATE_KEY_PREFIX + state, "1", Duration.ofMinutes(5));

        String authUrl = stravaOAuthService.buildAuthorizationUrl(state);
        log.debug("Redirecting to Strava OAuth: {}", authUrl);
        response.sendRedirect(authUrl);
    }

    // ── GET /auth/oauth/strava/callback ───────────────────────────────────────

    /**
     * Handles the Strava callback after user authorization.
     *
     * <p>Docs/06-sync-engine-spec.md §Strava OAuth Flow steps 3–5:
     * "User authorize → redirect back with code → Backend exchange code → access_token + refresh_token
     * → Store encrypted tokens in oauth_connections"
     *
     * @param code  authorization code from Strava
     * @param state CSRF state echoed back by Strava
     * @param error optional error from Strava (e.g., "access_denied" if user cancelled)
     */
    @GetMapping("/callback")
    public void handleCallback(@RequestParam(required = false) String code,
                               @RequestParam(required = false) String state,
                               @RequestParam(required = false) String error,
                               HttpServletResponse response) throws IOException {

        // Handle user-cancelled authorization
        if (error != null) {
            log.info("Strava OAuth cancelled by user: error={}", error);
            response.sendRedirect(appUrl + "/auth/error?reason=access_denied");
            return;
        }

        // Validate state to prevent CSRF (docs/08-auth-model.md §Security Checklist)
        if (state == null || !Boolean.TRUE.equals(redisTemplate.hasKey(STATE_KEY_PREFIX + state))) {
            log.warn("Strava OAuth callback received invalid or expired state");
            response.sendRedirect(appUrl + "/auth/error?reason=invalid_state");
            return;
        }
        redisTemplate.delete(STATE_KEY_PREFIX + state);

        if (code == null || code.isBlank()) {
            log.warn("Strava OAuth callback received no code");
            response.sendRedirect(appUrl + "/auth/error?reason=missing_code");
            return;
        }

        // Exchange code for tokens and resolve/create CoachFit user
        StravaOAuthUseCase.AuthResult result = stravaOAuthUseCase.handleCallback(code);

        // Set httpOnly refresh token cookie (docs/08-auth-model.md §JWT Structure)
        response.addHeader(HttpHeaders.SET_COOKIE, refreshCookie(result.rawRefreshToken()).toString());

        // Redirect frontend to a page that reads the access token from the URL.
        // The token is short-lived (1h) so URL transit is acceptable.
        // Frontend should immediately move it to in-memory storage.
        response.sendRedirect(appUrl + "/auth/callback?token=" + result.accessToken());
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private String generateState() {
        byte[] bytes = new byte[16];
        secureRandom.nextBytes(bytes);
        return HexFormat.of().formatHex(bytes);
    }

    private ResponseCookie refreshCookie(String rawToken) {
        return ResponseCookie.from(COOKIE_NAME, rawToken)
                .httpOnly(true)
                .secure(cookieSecure)
                .path(COOKIE_PATH)
                .maxAge(Duration.ofDays(30))
                .sameSite("Strict")
                .build();
    }

    private UserDto toUserDto(AuthUser user) {
        return new UserDto(user.id(), user.email(), user.fullName(), user.role(), user.tier());
    }
}
