package com.coachfit.auth.domain.model;

import java.time.Instant;
import java.util.UUID;

/**
 * Domain representation of a refresh token record.
 *
 * <p>Only the {@code tokenHash} (SHA-256 of the raw opaque value) is persisted;
 * the raw token is generated by the service, returned once in an httpOnly cookie,
 * and never stored.
 */
public record RefreshToken(
        UUID    id,
        UUID    userId,
        String  tokenHash,
        Instant expiresAt,
        Instant revokedAt   // null = valid
) {
    /** {@code true} if this token has been revoked or is past its expiry. */
    public boolean isValid() {
        return revokedAt == null && Instant.now().isBefore(expiresAt);
    }
}
